### ISSUE TITLE
Save / restore state when set saved / loaded

### ISSUE THREAD

**Issue by chrismcg** [chrismcg/Chrazy#1]
- Make sure everything that should be stored by Live is stored
- Need a flag to say whether this is a new instance or not
- If it's a new instance Chrazy should grab the current state of the Mopho and set the flag to false
- If it's not a new instance then Chrazy should send it's state to the Mopho instead

**Comment by chrismcg** [comment]
Think the logic should be something like:

Initialize a fresh instance - Midi port not sent so do nothing, PatchChanged set to default value of no
Midi port set and PatchChanged set to no - Get current patch from mopho
Control moved in live (could be via mopho front panel too) - Set PatchChanged to yes
Midi port set and PatchChanged set to yes - Send current patch to mopho

**Comment by acatcalledanarchy** [comment]
Hi Chris

Just came across this article which may be of use, regarding the above:

http://cycling74.com/2011/05/19/max-for-live-tutorial-adding-pattr-presets-to-your-live-session/

Hope you're having fun in the land of mayonnaise and chips!
