### ISSUE TITLE
Live Automation > Chrazy

### ISSUE THREAD

**Issue by acatcalledanarchy** [chrismcg/Chrazy#5]
Once automation has been recorded in Live, patch objects don't update to reflect automation data. Looking at the patch this would probably be due to stripping out NRPN's and having no means to transmit them to the knobs and menus etc

The following s nrpn_filter.js object by Pym may work here:

http://tetradev.blogspot.com/2010/03/nrpns-part-2-nrpns-in-ableton-with-max.html

**Comment by chrismcg** [comment]
Hrm, I'm using lh_midi so I can access the NPRNs properly, bypassing Live's limitations. Drawing the automation into a Live clip works. Was pretty sure that moving the controls worked to but obviously not! Will dig into why this evening. Thanks for the report.

**Comment by acatcalledanarchy** [comment]
Hi Chris

Yet again this may be me using the keyboard rather than the module. I had a
look through the back of the Mopho manual and it's starting to make sense to
me. Also, the mappings are almost identical for the Prophet '08!

Speak soon....

Sean

**Comment by chrismcg** [comment]
Recording automation in Arrangement works, and I see the dials move as the playhead moves through the automation. Are you talking about recording automation into clips in session view?

**Comment by acatcalledanarchy** [comment]
I was looking in arrangement view, I will try again and get back to you...

**Comment by acatcalledanarchy** [comment]
Ignore me!

Just booted it all up and it works! I was a little tired last night, maybe I
had Overdub selected or something. Apologies again on my part!

[?]

**Comment by chrismcg** [comment]
Cool, no worries. Glad it's working! :)

**Comment by acatcalledanarchy** [comment]
You can't believe how happy you've made me. I'm going to have a quick fiddle
to see if can get it to work with my Prophet, which would be absolutely
insane - I spent a good couple of weeks writing my own patch for the Prophet
which was seriously flawed to be honest. Seeing what you've done has given
me a massive leap in understanding how the whole SysEx thing works, once I
converted the binary values in the manual into decimal which then matched
the contents of your _match_ object... Revelation upon revelation!
