### ISSUE TITLE
Display and edit patch name

### ISSUE THREAD

**Issue by chrismcg** [chrismcg/Chrazy#7]
Just ignoring atm, will need to do before #1 otherwise can't send name to Mopho

**Comment by acatcalledanarchy** [comment]
Is there a way of getting an array of all bank and patch names..? This would be handy to select Mopho patch to edit from Live...

**Comment by chrismcg** [comment]
I think the only way is to grab all the patches, definitely doable though.

**Comment by acatcalledanarchy** [comment]
Hmmm, so you would have to loop through all the banks and patches and request the whole of the programme parameters to get the names - wow!
